### PR TITLE
Updated type annotations to work with numpy 1.20

### PR DESCRIPTION
**Pull request by peastman**
This PR fixes all the mypy errors when using numpy 1.20.  It does *not* update anything to actually install numpy 1.20, and it doesn't attempt to make the code work.  That probably won't be possible until TensorFlow gets updated.  I'm creating this now so these changes will be here once we're ready for them.

### CODE REVIEW

**Comment by peastman** [comment]
By the way, this requires Mypy 0.902 which was just released today.  If you use an older version, you'll still get some errors.

**Review by rbharath — APPROVED** [review]
Looks good! If this is ready, let's go ahead and merge this in so we have the road cleared for bumping to numpy 1.20

**Comment by peastman** [comment]
We should wait until after updating to 1.20.  Otherwise this will completely break master, since `numpy.typing` doesn't exist.

**Comment by peastman** [comment]
I just pushed lots more changes.  I now have mypy passing with the latest code and numpy 1.21.  To keep everything working, this requires upgrading numpy, which requires upgrading TensorFlow as well.  So this needs to get combined with #2783 and #2789.  We could merge them one at a time, which will temporarily leave the code in a broken state.  Alternatively, @arunppsg could pull these changes into one of the other PRs so they get merged together.

@VIGNESHinZONE could you take a look at the line in lcnn_featurizer.py where I added `# type: ignore` to make sure it's really correct?  That line is passing a numpy array to `pymatgen.core.Molecule`.  The annotations for that class say it can take a sequence of arrays, but not a single array, so mypy reports an error.

**Comment by rbharath** [comment]
We just merged in #2789 which updates tensorflow, so I think if we rebase this PR we might be good to go ahead and merge in. We could also fold these updates into #2783 (cc @arunppsg)

**Comment by peastman** [comment]
I merged changes from the main branch.

**Comment by rbharath** [comment]
I took a look at the CI and I'm seeing some failure of the type:

```
Run mypy --install-types
error: Can't determine which types to install with no files to check (and no cache from previous mypy run)
Error: Process completed with exit code 2.
```

Is this an error you've seen before with mypy? I haven't run `mypy --install-types` before so unsure about the behavior

**Comment by peastman** [comment]
No, this is the first time I've ever used it.  Mypy was reporting errors in one class due to type stubs not being installed.  The error message said to use that command to install them.  I ran it and the error went away, so I added it to the script.  I guess it can only be used after you've already run mypy and gotten errors.

**Comment by rbharath** [comment]
I think this is almost ready to merge in but I'm still seeing a mysterious mypy error on Ubuntu 3.7 core run:

```
Run mypy -p deepchem
deepchem/feat/material_featurizers/lcnn_featurizer.py:674: error: Argument 2 to "Molecule" has incompatible type "ndarray[Any, dtype[Any]]"; expected "Sequence[Sequence[float]]"
Found 1 error in 1 file (checked 338 source files)
Error: Process completed with exit code 1.
```

**Comment by peastman** [comment]
That's the line I asked @VIGNESHinZONE to take a look at.  But I added a `# type: ignore` comment to it.  Shouldn't mypy be ignoring it?

**Comment by peastman** [comment]
As soon as I got everything working on numpy 1.21, they released 1.22 which caused lots more errors.  I hope that isn't going to happen with every update.  I have all of them fixed now.  There are still a few CI failures, but I'm not sure if they have anything to do with this PR.  A few of the Windows builds seem to have problems.

**Comment by rbharath** [comment]
@peastman This is great! I'm excited to get up to np 1.22 since that activate the new generic array API.

@arunppsg I think that none of the failures have to do with this PR. Could you take a quick look when you get a chance and confirm? If so, I think we can go ahead and merge in

**Comment by arunppsg** [comment]
Great from my side! Now, we can possibly drop `env_torch.yml` and `env_jax.yml` and just use `env_common.yml` - the only reason we have the first two are for specifying numpy version. But, we can also do that later in a different PR.

**Comment by peastman** [comment]
Thanks!  I'll merge it then.
