### ISSUE TITLE
would I like to see when deepchem for win will be available, thanks

### ISSUE THREAD

**Issue by xgxofdream** [deepchem/deepchem#1725]
**Description:**

- DeepChem Version:
- Platform:

```
Your code sample here
```

**Comment by rbharath** [comment]
At present, we don't have plans to add Windows support, but we are in the process of trying to identify development priorities. We'd love to have your feedback on this issue https://github.com/deepchem/deepchem/issues/1722 if you think Windows support would make a major difference to you.

**Comment by JZuegg** [comment]
I have been running DeepChem on Win10, including DeepChem 2.3.0, using Anaconda with python 3.6 and mostly conda installs:

conda create -name DeepChemTF14 python=3.6

conda config --add channels conda-forge 	
conda install jupyter	
conda install pandas 	
conda install seaborn	
conda install scikit-learn	
conda install -c rdkit rdkit	
_**some extras (not required for DC)**_
conda install -c oddt oddt	
conda install molvs	
conda install biopython
conda install cx_oracle
conda install mysql-connector-python

**_with some pip installtion/cleanup** 
conda install tensorflow-gpu=1.14.0	
pip uninstall numpy
conda install numpy=1.16.4
pip install keras	

**_and for DeepChem I install it from GitHu_b**:
conda install -y setuptools
conda install -y pbr
git clone https://github.com/deepchem/deepchem 
cd deepchem
python setyp.py install

**Comment by rbharath** [comment]
@JZuegg awesome, glad to hear you have a working setup! 

@xgxofdream I'm planning on working towards formal windows support in the next couple releases. I'm doing some general DeepChem planning. Will update this issue once that's complete with more details.

**Comment by Sparklingredstar** [comment]
> 我一直在Win10上运行DeepChem，包括DeepChem 2.3.0，将Anaconda与python 3.6一起使用，并且大多数使用conda安装：
> 
> 康达创建-name DeepChemTF14 python = 3.6
> 
> conda配置-添加通道conda-
> forge conda安装jupyter conda
> 安装pandas
> conda安装seaborn conda
> install scikit-learn
> conda install -c rdkit rdkit
> _**一些额外功能（DC不需要）**_
> conda install -codntodd conda
> 安装molvs conda
> 安装biopython
> conda安装cx_oracle conda
> 安装mysql-connector-python
> 
> **_with一些pip安装/清理**
> conda install tensorflow-gpu = 1.14.0
> pip卸载numpy
> conda install numpy = 1.16.4
> pip install keras
> 
> **_and对于DeepChem，我从GitHu_b安装它**：
> conda
> install -y setuptools conda install -y pbr
> git clone https://github.com/deepchem/deepchem
> cd deepchem
> python setyp.py安装

I successfully installed on Win10 according to your method, but AttributeError occurred when importing deepchem: module 'tensorflow' has no attribute 'function'. Does the current version need tensorflow 2.0? Thank you so much!

**Comment by rbharath** [comment]
@Sparklingredstar Did you install from github? If so, yes, we just upgraded the latest version to TF2.1. I'd recommend using the stable release version DeepChem 2.3.0 instead (which uses TF1.14). HEAD is in active development and is unfortunately partially broken (we're working on fixing TF2.1 upgrade issues).

**Comment by Sparklingredstar** [comment]
> @Sparklingredstar Did you install from github? If so, yes, we just upgraded the latest version to TF2.1. I'd recommend using the stable release version DeepChem 2.3.0 instead (which uses TF1.14). HEAD is in active development and is unfortunately partially broken (we're working on fixing TF2.1 upgrade issues).

Yes, I will try to download deepchem 2.3.0 from github, thanks for your help

**Comment by nd-02110114** [comment]
I seem this issue is fixed.
