### ISSUE TITLE
MordredDescriptors: Exception message: cannot import name 'CalcPBF' from 'rdkit.Chem.rdMolDescriptors' 

### ISSUE THREAD

**Issue by behroozazarkhalili** [deepchem/deepchem#2569]
## 🐛 Bug

When using MordredDescriptors I faced with the following warning and nothing return:
Exception message: cannot import name 'CalcPBF' from 'rdkit.Chem.rdMolDescriptors' (/usr/lib/python3/dist-packages/rdkit/Chem/rdMolDescriptors.cpython-38-x86_64-linux-gnu.so)

## To Reproduce

```
import deepchem as dc
example_smiles = ['CCCCO', 'CCC', 'CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(=O)(=O)N)C(F)(F)F']
getattr(dc.feat, Mol2VecFingerprint)(example_smiles)
```

## Environment

* OS: Linux Mint 20.1
* Python version: 3.8.8
* DeepChem version:  2.6.0.dev
* RDKit version (optional): 2019.09.1
* TensorFlow version (optional): 2.4
* PyTorch version (optional): 1.7
* Any other relevant information:

**Comment by rbharath** [comment]
Marked this as a bug and open for contribution. Thanks for the report!

**Comment by zulkifli25** [comment]
learn

**Comment by behroozazarkhalili** [comment]
Any update?

**Comment by arunppsg** [comment]
I am not able to reproduce this error. Can you try upgrading your rdkit version? It works fine with mordred version 1.2.0 and rdkit version 2020.09.1.

**Comment by behroozazarkhalili** [comment]
I'll do it tomorrow and let you know tomorrow.
Thanks for your follow up.

Best Regards,
Behrooz Azarkhalili
