### ISSUE TITLE
 dropout() got an unexpected keyword argument 'rate'

### ISSUE THREAD

**Issue by Karunakar444** [deepchem/deepchem#1675]
**Description:**

- DeepChem Version:
- Platform:

```
Your code sample here
```

**Comment by Karunakar444** [comment]
Hello!
I was going through Modelling Solubility tutorial. When I was running the code, I met with the following error:
**dropout() got an unexpected keyword argument 'rate'**
Can somebody help me with this?
Thanks in advance.

**Comment by peastman** [comment]
A recent version of TensorFlow changed the API for dropout, so you need to be sure you're using the correct version of TensorFlow for the version of DeepChem you have.  What versions are you using?  DeepChem 2.2 was written to work with TensorFlow 1.12.  DeepChem 2.3, which we hope to get out soon, will be written for TensorFlow 1.14.

**Comment by Karunakar444** [comment]
I think I am using Tensorflow 1.14 because I have installed it recently. Could u please tell me how to get Tensorflow 1.12? I tried installing 1.12 version but it was of no use.
Thanks.

**Comment by Karunakar444** [comment]
I am using Anaconda environment

**Comment by Karunakar444** [comment]
I have installed TensorFlow 1.12 and tried running the code again. I am still getting the same error.

**Comment by peastman** [comment]
Did you intend to close the issue?  Does that mean you solved it?

**Comment by Karunakar444** [comment]
Yeah...I sorted out.Thanks for the help!
