### ISSUE TITLE
 deepchem/examples/pdbbind_nnscore.py   can't import FeaturilizedSamples

### ISSUE THREAD

**Issue by elliotnam** [deepchem/deepchem#248]
on source pdbbind_nnscore.py 

File "pdbbind_nnscore.py", line 15, in <module>
    from deepchem.featurizers.featurize import FeaturizedSamples
ImportError: cannot import name FeaturizedSamples

**Comment by rbharath** [comment]
Good catch. This is an outdated example. Please check out the examples in `deepchem/examples/pdbbind` for working pdbbind examples. I'll go ahead and remove this file in a follow-up PR.

**Comment by rbharath** [comment]
Just removed broken example in #242.

**Comment by elliotnam** [comment]
Hi
when I run pdbbind_tf.py
I can't find this data file under datasets/pdbbind/INDEX_core_data.2013'
where can i get it

**Comment by rbharath** [comment]
Good point. This dataset should be added in or directions should be given on how to get the data. I've reopened the issue, and will try to fix in a follow-on PR.

**Comment by hainm** [comment]
@rbharath is there any example  that does not require long run?

**Comment by rbharath** [comment]
@hainm Yes, the Tox21 dataset should run within 15 minutes on a GPU. On CPU though, this would likely be something like 3 hours.

**Comment by hainm** [comment]
Do you intend to write a small example for CPU? requiring GPU to play with `deepchem` is too much for users. :D

**Comment by rbharath** [comment]
Fair enough :-). Unfortunately, DeepChem is currently primarily a library for training deep-learning models conveniently, which currently requires a GPU to be practical. I do have plans to distributed pre-trained models (which users would be able to use on CPU), but that's probably a few months out at the earliest.

**Comment by rbharath** [comment]
Fixed by #327
