### ISSUE TITLE
AttributeError: module 'deepchem.models.tensorgraph' has no attribute 'fcnet'

### ISSUE THREAD

**Issue by soerendip** [deepchem/deepchem#1720]
I am trying out this tutorial: 

    https://deepchem.io/docs/notebooks/Explaining_Tox21.html

When I run that code I get:

> AttributeError: module 'deepchem.models.tensorgraph' has no attribute 'fcnet'

I installed deepchem with 

    python setup.py develop

with `deepchem==2.3.1.dev10`.

And installing it with pip or conda.

**Comment by peastman** [comment]
@rbharath it looks like the website still has the old DeepChem 2.2 version of the tutorials.  Can we update them?

@soerendip You can find the up to date version of that tutorial at https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Explaining_Tox21.ipynb.  It works correctly with 2.3.

**Comment by rbharath** [comment]
I'm working on overhauling the website. It looks like it will take a bit of doing. In the meanwhile, I'd recommend looking at the up to date tutorials on the github

**Comment by rbharath** [comment]
I've updated the website to point at the most recent tutorials
