### ISSUE TITLE
module 'tensorflow.train' has no attribute 'CheckpointManager'

### ISSUE THREAD

**Issue by Karunakar444** [deepchem/deepchem#1678]
Hi!
I am trying to run code of the Synthetic_Feasibility_Scoring given deepchem tutorial. But I am getting the following error:
**module 'tensorflow.train' has no attribute 'CheckpointManager'**
I am using the following versions:
deepchem=2.2
Tensorflow = 1.12
Could somebody help me with this?
![Screenshot from 2019-09-07 14-50-26](https://user-images.githubusercontent.com/54398887/64472630-049d9a00-d17f-11e9-9f9c-1cf0d4065da3.png)

**Comment by peastman** [comment]
I take it you're using the latest code from the repository?  That's written to work with TF 1.14.  DeepChem 2.2 does not use CheckpointManager.  That code was added later.

**Comment by Karunakar444** [comment]
Thanks, it worked!

**Comment by Karunakar444** [comment]
Could you please tell me how to give input to find the feasibility score?
I tried giving the input but it was showing some error.
Thanks in advance.

**Comment by peastman** [comment]
>  I tried giving the input but it was showing some error.

What was the error?

**Comment by Karunakar444** [comment]
It was showing it cannot take given complex molecule as input.I tried
giving a pair of molecules, it is still showing the error.
If u don't mind , could you please tell me how to give the input.If
possible, code also.Please.
Thanks in advance.

**Comment by peastman** [comment]
Please provide the exact text of the error message.  Just copy and paste the full output of the program.

**Comment by Karunakar444** [comment]
![Screenshot from 2019-09-17 23-39-32](https://user-images.githubusercontent.com/54398887/65067672-ac4b7100-d9a4-11e9-864b-2290b97a21e9.png)
This is the error I am getting

**Comment by Karunakar444** [comment]
I am getting the following error:
![Screenshot from 2019-09-22 14-52-22](https://user-images.githubusercontent.com/54398887/65385143-ae1c8800-dd48-11e9-87b4-209dc3a859c4.png)

**Comment by VIGS25** [comment]
`model.predict_mols()` expects a `Mol` object but the input given was a SMILES string. Hence the function signatures didn't match and the error. 

Use this instead:

```
from rdkit import Chem
model.predict_mols(Chem.MolFromSmiles("Cc1ccccc1"))
```
